#!/usr/bin/env python

import rospy
from intermittent_monitoring.area import *

if __name__ == '__main__':
    area = Area(area=3, decay_rate=0.005, t_operation=1000)
    area.run_operation()
    rospy.spin()