#!/usr/bin/env python

"""
[WORK]
Inputs:
1. Receives battery level from robot

Process:
> Monitors the battery levels from motion and stores in an array

Outputs:
> Possibly a graph of battery levels throughout the duration of the operation

"""

import rospy
from intermittent_monitoring.monitor_battery import *

if __name__ == '__main__':

    battery_listener = BatteryLevelListener(1)
    result = battery_listener.save_recorded_array()
    #print("Stored batt data:", result)
    rospy.spin()
